-- DermaSense master schema (11 tables)
-- PostgreSQL schema for Neon startup initialization

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    age INTEGER,
    gender VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skin_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    skin_type VARCHAR(50) NOT NULL,
    concern VARCHAR(255),
    sensitivity_level INTEGER,
    acne_prone BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_skin_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS analysis (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    image_url VARCHAR(500),
    detected_skin_type VARCHAR(50),
    confidence_score DECIMAL(5,4),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analysis_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_analysis_confidence
        CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1))
);

CREATE TABLE IF NOT EXISTS skin_conditions (
    condition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS analysis_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT NOT NULL,
    condition_id BIGINT NOT NULL,
    severity INTEGER NOT NULL,
    CONSTRAINT fk_analysis_conditions_analysis
        FOREIGN KEY (analysis_id) REFERENCES analysis (analysis_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_analysis_conditions_condition
        FOREIGN KEY (condition_id) REFERENCES skin_conditions (condition_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_analysis_condition_pair UNIQUE (analysis_id, condition_id),
    CONSTRAINT chk_analysis_conditions_severity
        CHECK (severity >= 1 AND severity <= 10)
);

CREATE TABLE IF NOT EXISTS recommendations (
    rec_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT fk_recommendations_analysis
        FOREIGN KEY (analysis_id) REFERENCES analysis (analysis_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_recommendation_type
        CHECK (type IN ('product', 'routine', 'diet'))
);

CREATE TABLE IF NOT EXISTS products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    brand VARCHAR(120),
    skin_type_target VARCHAR(50),
    ingredients TEXT,
    price DECIMAL(10,2),
    image_url VARCHAR(500),
    CONSTRAINT chk_products_price
        CHECK (price IS NULL OR price >= 0)
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT,
    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON DELETE CASCADE,
    CONSTRAINT chk_reviews_rating
        CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE IF NOT EXISTS chat_logs (
    chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    response TEXT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_logs_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS progress (
    progress_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    condition_id BIGINT NOT NULL,
    severity_before INTEGER NOT NULL,
    severity_after INTEGER NOT NULL,
    date DATE NOT NULL,
    CONSTRAINT fk_progress_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_progress_condition
        FOREIGN KEY (condition_id) REFERENCES skin_conditions (condition_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_progress_severity_before
        CHECK (severity_before >= 1 AND severity_before <= 10),
    CONSTRAINT chk_progress_severity_after
        CHECK (severity_after >= 1 AND severity_after <= 10)
);

CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_favorites_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_favorites_user_product UNIQUE (user_id, product_id)
);

-- Indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_skin_profiles_user_id ON skin_profiles (user_id);
CREATE INDEX IF NOT EXISTS idx_analysis_user_id ON analysis (user_id);
CREATE INDEX IF NOT EXISTS idx_analysis_created_at ON analysis (created_at);
CREATE INDEX IF NOT EXISTS idx_analysis_conditions_analysis_id ON analysis_conditions (analysis_id);
CREATE INDEX IF NOT EXISTS idx_analysis_conditions_condition_id ON analysis_conditions (condition_id);
CREATE INDEX IF NOT EXISTS idx_recommendations_analysis_id ON recommendations (analysis_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews (user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_chat_logs_user_id ON chat_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_progress_user_id ON progress (user_id);
CREATE INDEX IF NOT EXISTS idx_progress_condition_id ON progress (condition_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user_id ON favorites (user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_product_id ON favorites (product_id);
